name: test GitHub Actions

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: huynhlan22/autotests-ci
